global:
  scrape_interval:     15s  # ターゲットをどのくらいの頻度でスクレイピングするかを設定します
  evaluation_interval: 15s  # ターゲットのアップダウンをどのくらいの間隔で評価するかを設定します
scrape_configs:
  - job_name: 'node-exporter'  # 監視対象の名称を設定します。
    static_configs:
      - targets:
        - monitoring:9100  # Prometheus自身を監視目標にしています。
        - node01:9100
        - node02:9100
        - stake01:9100
        - stake02:9100
  - job_name: 'Eth-Mainnet-Geth'  # 監視対象の名称を設定します。
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets:
        - node01:6060
        - node02:6060
  - job_name: 'validator'
    static_configs:
      - targets:
        - stake01:8081
  - job_name: 'beacon node'
    static_configs:
      - targets:
        - node01:8080
        - node02:8080
rule_files: # アラートルールの設定
  - /etc/prometheus/alert.yml
alerting: # アラート設定
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093
